export const LINKTREE_THEMES = {
    midnight: {
        id: "midnight",
        name: "Midnight",
        description: "Dark and elegant",
        background: "bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950",
        card: "bg-slate-800/50 hover:bg-slate-700/60 border-slate-700/50",
        text: "text-white",
        textSecondary: "text-slate-300",
        textMuted: "text-slate-400",
        accent: "text-blue-400",
        button: "bg-slate-800 hover:bg-slate-700 text-white border-slate-600",
        socialButton: "bg-slate-800/80 hover:bg-slate-700 text-white",
        font: "font-sans",
    },
    sunset: {
        id: "sunset",
        name: "Sunset",
        description: "Warm and vibrant",
        background: "bg-gradient-to-br from-orange-500 via-pink-500 to-purple-600",
        card: "bg-white/20 hover:bg-white/30 border-white/30 backdrop-blur-sm",
        text: "text-white",
        textSecondary: "text-white/90",
        textMuted: "text-white/70",
        accent: "text-yellow-200",
        button: "bg-white/20 hover:bg-white/30 text-white border-white/40 backdrop-blur-sm",
        socialButton: "bg-white/20 hover:bg-white/30 text-white backdrop-blur-sm",
        font: "font-sans",
    },
    forest: {
        id: "forest",
        name: "Forest",
        description: "Natural and calm",
        background: "bg-gradient-to-br from-emerald-900 via-green-800 to-teal-900",
        card: "bg-emerald-800/40 hover:bg-emerald-700/50 border-emerald-600/40 backdrop-blur-sm",
        text: "text-white",
        textSecondary: "text-emerald-100",
        textMuted: "text-emerald-200/70",
        accent: "text-lime-300",
        button: "bg-emerald-700/60 hover:bg-emerald-600/70 text-white border-emerald-500/50",
        socialButton: "bg-emerald-800/60 hover:bg-emerald-700/70 text-white",
        font: "font-sans",
    },
    ocean: {
        id: "ocean",
        name: "Ocean",
        description: "Deep and serene",
        background: "bg-gradient-to-br from-blue-950 via-cyan-900 to-blue-900",
        card: "bg-cyan-800/30 hover:bg-cyan-700/40 border-cyan-500/30 backdrop-blur-sm",
        text: "text-white",
        textSecondary: "text-cyan-100",
        textMuted: "text-cyan-200/70",
        accent: "text-sky-300",
        button: "bg-cyan-800/50 hover:bg-cyan-700/60 text-white border-cyan-500/40",
        socialButton: "bg-cyan-800/50 hover:bg-cyan-700/60 text-white",
        font: "font-sans",
    },
    lavender: {
        id: "lavender",
        name: "Lavender",
        description: "Soft and dreamy",
        background: "bg-gradient-to-br from-purple-100 via-pink-50 to-indigo-100",
        card: "bg-white/70 hover:bg-white/90 border-purple-200/60 backdrop-blur-sm shadow-sm",
        text: "text-purple-900",
        textSecondary: "text-purple-700",
        textMuted: "text-purple-500",
        accent: "text-pink-600",
        button: "bg-white/80 hover:bg-white text-purple-900 border-purple-200 shadow-sm",
        socialButton: "bg-purple-100/80 hover:bg-purple-200/80 text-purple-800",
        font: "font-sans",
    },
} as const;

export type LinktreeThemeId = keyof typeof LINKTREE_THEMES;
export type LinktreeTheme = (typeof LINKTREE_THEMES)[LinktreeThemeId];

export const getTheme = (themeId: string): LinktreeTheme => {
    return LINKTREE_THEMES[themeId as LinktreeThemeId] || LINKTREE_THEMES.midnight;
};
