name: trimium

services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - trimium-network

  app:
    image: ghcr.io/iamdevtrivedi/trimium-app:current
    restart: unless-stopped
    ports:
      - "5003:5003"
    env_file:
      - .env.production
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trimium-network

networks:
  trimium-network:
    driver: bridge

volumes:
  redis_data:
