name: CI/CD

on: 
  push: 
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint check
        run: pnpm run lint

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier formatting check
        run: pnpm run format:check

  detect-changes:
    runs-on: ubuntu-latest
    needs: [lint, prettier]

    outputs:
      client: ${{ steps.changes.outputs.client }}
      server: ${{ steps.changes.outputs.server }}
    
    steps:
      - uses: actions/checkout@v6

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'
              - 'package.json'

  deploy-client:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.client == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-server:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.server == 'true' && vars.DEPLOY_TO_EC2 == 'true'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            source ~/.nvm/nvm.sh        

            echo "Pulling latest code..." 
            cd /home/${{ secrets.EC2_USER }}/my-projects/Trimium
            git pull origin main

            echo "Installing dependencies at root level"
            pnpm install --frozen-lockfile

            echo "Installing dependencies at server level..."
            cd server 
            pnpm install --frozen-lockfile

            echo "Building server..."
            NODE_OPTIONS="--max-old-space-size=1024" pnpm run build
            
            echo "Downloading GeoIP database"
            cd ..
            pnpm run download:geoip

            CURRENT_HASH=$(git rev-parse HEAD)
            cd ./server/release/
            PREVIOUS_HASH=$(find . -mindepth 1 -maxdepth 1 -type d -printf '%T@ %f\n' | sort -nr | head -n 1 | cut -d' ' -f2)

            NEW_RELEASE_DIR="$(pwd)/$CURRENT_HASH"
            PREVIOUS_RELEASE_DIR="$(pwd)/$PREVIOUS_HASH"
            mkdir -p "$NEW_RELEASE_DIR"
            cd ..
            cp -r ./dist "$NEW_RELEASE_DIR/"
            rm -rf dist

            ln -sfn "$(pwd)/shared/.env.production" "$NEW_RELEASE_DIR"
            ln -sfn "$(pwd)/shared/logs" "$NEW_RELEASE_DIR"

            ln -sfn "$NEW_RELEASE_DIR" "$(pwd)/current"

            pm2 restart trimium-server
            pm2 status trimium-server | grep -q "online"

            HEALTH_ENDPOINT="http://localhost:5000/api/v1/health"

            HEALTH_CHECK_PASSED=false

            for i in {1..10}; do
              if curl -s "$HEALTH_ENDPOINT" | grep -q "OK"; then
                HEALTH_CHECK_PASSED=true
                break
              fi
              echo "Health check failed. Retrying in 5 seconds..."
              sleep 5
            done


            if [ "$HEALTH_CHECK_PASSED" = true ]; then
              echo "Deployment successful and server is healthy."
              exit 0
            fi

            ln -sfn "$PREVIOUS_RELEASE_DIR" "$(pwd)/current"
            pm2 restart trimium-server

            echo "Deployment failed. Rolled back to previous release."
            exit 1